root_dir: "C:/crossinsights_project/crossinsights"

data:
  raw:
    users: "C:/crossinsights_project/crossinsights/data/raw/users.csv"
    movies: "C:/crossinsights_project/crossinsights/data/raw/movies.csv"
    ratings: "C:/crossinsights_project/crossinsights/data/raw/ratings.csv"
  processed:
    users: "C:/crossinsights_project/crossinsights/data/processed/users_clean.csv"
    movies: "C:/crossinsights_project/crossinsights/data/processed/movies_clean.csv"
    ratings: "C:/crossinsights_project/crossinsights/data/processed/ratings_clean.csv"
    knn_recommendations: "C:/crossinsights_project/crossinsights/data/processed/knn_recommendations.csv" # جديد

models:
  output_dir: "C:/crossinsights_project/crossinsights/models/"
  svd:
    n_factors: 100
    n_epochs: 20
  knn: # جديد
    k_neighbors: 5
    similarity_metric: "cosine"

eda:
  notebook: " 更新 C:/crossinsights_project/crossinsights/analysis/eda.ipynb"
